on: [push]

jobs:
  qovery_deployment_job:
    runs-on: ubuntu-latest
    name: A job to deploy app on Qovery
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Qovery action step
        uses: Qovery/qovery-action@main
        id: qovery
        with:
          qovery-organization-id: ${{secrets.QOVERY_ORGANIZATION_ID}} 
          qovery-project-id: ${{secrets.QOVERY_PROJECT_ID}}
          qovery-environment-id: ${{secrets.QOVERY_ENVIRONMENT_ID}}
          qovery-application-ids: ${{secrets.QOVERY_APPLICATION_IDS}}
          qovery-api-token: ${{secrets.QOVERY_API_TOKEN}} 
