on: [push]

jobs:
  qovery_deployment_job:
    runs-on: ubuntu-latest
    name: A job to deploy app on Qovery
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qovery action step
        uses: Qovery/qovery-action@main
        id: qovery
        with:
          qovery-organization-id: cf8e78e6-159b-45b6-bfb5-2430c9505080
          qovery-organization-name: Qovery tests Scaleway
          qovery-project-name: Tetris demo app
          qovery-environment-name: dev
          qovery-application-names: tetris
          qovery-api-token: ${{secrets.QOVERY_API_TOKEN}}
          qovery-application-commit-id: ${{ github.sha }}
